%YAML:1.0

# algorithm's hyper parameters
# pose_initialization_method: pro
pose_initialization_method: mix
translation_initialize_scale: 1
rotation_initialize_scale: 1
max_iteration: 20
scaling_coefficient1: 0.18
scaling_coefficient2: 0.09
init_fitness: 0.5
momentum: 0.9
scaling_inherit_directly: 0
enough_depth_ratio: 0.5

# save results
save_trajectory: 1
save_scene: 1